namespace MCServer
{
    public enum Biomes
    {
        Ocean,
        Plains,
        Desert,
        Mountains,
        Forest,
        Taiga,
        Swamp,
        River,
        NetherWastes,
        TheEnd,
        FrozenOcean,
        FrozenRiver,
        SnowyTundra,
        SnowyMountains,
        MushroomFields,
        MushroomFieldShore,
        Beach,
        DesertHills,
        WoodedHills,
        TaigaHills,
        MountainEdge,
        Jungle,
        JungleHills,
        JungleEdge,
        DeepOcean,
        StoneShore,
        SnowyShore,
        BirchForest,
        BirchForestHills,
        DarkForest,
        SnowyTaiga,
        SnowyTaigaHills,
        GiantTreeTaiga,
        GiantTreeTaigaHills,
        WoodedMountains,
        Savanna,
        SavannaPlateau,
        Badlands,
        WoodedBadlandsPlateau,
        BadlandsPlateau,
        SmallEndIslands,
        EndMidlands,
        EndHighlands,
        EndBarrens,
        WarmOcean,
        LukewarmOcean,
        ColdOcean,
        DeepWarmOcean,
        DeepLukewarmOcean,
        DeepColdOcean,
        DeepFrozenOcean,
        TheVoid = 127,
        SunflowerPlains = 129,
        DesertLakes = 130,
        GravellyMountains,
        FlowerForest,
        TaigaMountains,
        SwampHills,
        IceSpikes = 140,
        ModifiedJungle = 149,
        ModifiedJungleEdge = 151,
        TallBirchForest = 155,
        TallBirchHills,
        DarkForestHills,
        SnowyTaigaMountains,
        GiantSpruceTaiga = 160,
        GiantSpruceTaigaHills,
        ModifiedGravellyMountains,
        ShatteredSavanna,
        ShatteredSavannaPlateau,
        ErodedBadlands,
        ModifiedWoodedBadlandsPlateau,
        ModifiedBadlandsPlateau,
        BambooJungle,
        BambooJungleHills,
        SoulSandValley,
        CrimsonForest,
        WarpedForest,
        BasaltDeltas
    }
}